### ISSUE TITLE
surface boundary shrinkage after remeshing

### ISSUE THREAD

**Issue by xiaolong7** [BrunoLevy/geogram#29] opened 2022-11-02 17:36 UTC
Hello, I tried the isotropic remeshing algorithm (tri_size_adapt=0, tri_shape_adapt=0) on a surface mesh with boundary and found that the **surface boundary shrinks after remeshing**, as shown in the below screenshot. Do you have any idea why that happened? Is there any way to preserve the original surface boundary as much as possible? Thank you!

![image](https://user-images.githubusercontent.com/104316304/199561291-af511fff-0745-4327-aa3e-a116bca58b06.png)

**Comment by BrunoLevy** [comment] 2022-11-07 15:22
Yes, it is due to the remeshing method that I'm using (Voronoi Parallel Linear Enumeration), that places the points in such a way that it optimizes the sampling of the shape (w.r.t. a certain measure of optimality), and this optimal sampling does not necessarily have the points on the surface.

To mitigate this, it is necessary to reproject the points onto the initial surface. It will be supported in v1.8.2. A release candidate will be pushed soon (within a couple of weeks the latest)

**Comment by xiaolong7** [comment] 2022-11-07 15:57
> Yes, it is due to the remeshing method that I'm using (Voronoi Parallel Linear Enumeration), that places the points in such a way that it optimizes the sampling of the shape (w.r.t. a certain measure of optimality), and this optimal sampling does not necessarily have the points on the surface.
> 
> To mitigate this, it is necessary to reproject the points onto the initial surface. It will be supported in v1.8.2. A release candidate will be pushed soon (within a couple of weeks the latest)

Got it. Thank you!

**Comment by BrunoLevy** [comment] 2022-11-10 06:07
On its way, see [this thread](https://twitter.com/BrunoLevy01/status/1590457620246036480). We'll see whether this works (and now we have non-regression tests to make sure I'm not going to break anything). If it works it will be in v1.8.2.

**Comment by BrunoLevy** [comment] 2022-11-10 18:34
![image](https://user-images.githubusercontent.com/19478253/201178259-b491cd3d-f34e-4f24-99e0-d6686743578c.png)
Nearly there it seems !!

**Comment by BrunoLevy** [comment] 2022-11-10 19:06
Pushed it ! Would you test and tell me ?

**Comment by xiaolong7** [comment] 2022-11-11 00:40
> Pushed it ! Would you test and tell me ?

I tried it and it has improved a lot! Thanks a lot!
![image](https://user-images.githubusercontent.com/104316304/201235340-4e02c3d8-fae6-4e18-b59f-a81e5eb1fce5.png)

**Closed** 2022-11-11 08:56 UTC
